id: P8882F8F8
initial_creation_type: input
source_metadata:
  title: Nepal Series
  language: bo
  description: 'Texts related to the kingdom of Nepal, known to Tibetans as the ''land
    of wool'' (bal yul):'
  volume:
    042b771373a84487a42ee336d807b763:
      title: 'Melodious Tambura of Delight: A Guide to Māratika Cave, Supreme Site
        of Immortality'
      parent: Guides
    8aa14cfb955a4d2884239f4b2a4caea6:
      title: A Short Guide to Yangleshö in Nepal
      parent: Guides
    b1e2ebe002b0487c92931e6dd2741e6f:
      title: 'Liberation Upon Hearing: The History of the Great Jarung Kashor Stūpa'
      parent: History
    3b702ea224124070b73c477b7e8447c4:
      title: A Brief Petitionary Offering to the Mātṛkā Pukkasī, Local Protectress
        of the Jarung Kashor Stūpa
      parent: Offering
    930d97c1af7d443fa7372844c6e0f454:
      title: In Praise of Yangleshö in Nepal
      parent: Praise
    6c794e1d283643febc8d7181970189cc:
      title: 'The White Lotus: In Praise of Lumbinī'
      parent: Praise
    c4a58ca21f8a4e55b6a0dbcdeac31800:
      title: In Praise of the Hidden Valley of Kyimolung
      parent: Praise
    2ca3711c94644bea9d8cad618a2a6dff:
      title: Prayer to the Three Great Stūpas of Kathmandu
      parent: Prayers
    29c61aaf210b4a278a437c6121451b8e:
      title: A Prayer to the Stūpa of Jarung Khashor in Boudha
      parent: Prayers
    6921d6a4b46f41d6b9b2ce0a6916b3b2:
      title: A Prayer to the Svayambhū Stūpa in Nepal
      parent: Prayers
    e58198c4c1b24b5a8e52a4713afa52f0:
      title: A Prayer to the Three Stūpas of Nepal
      parent: Prayers
    279e17a2fc414cff90ab8b9bfab10b10:
      title: Prayer of Aspiration to the Stūpa Commemorating the Bodily Sacrifice
        to the Tigress
      parent: Prayers
    907c1f4e9e074b6f8e2f72f0b856c054:
      title: 'Auspicious Dance of Longevity: A Song for Touring the Sacred Sites of
        Nepal'
      parent: Songs
    184a6c5efe3a477c8aee5af83ae18698:
      title: Upon Arriving at Yangleshö
      parent: Songs
created_at: '2022-03-01T04:47:23.841514'
last_modified_at: '2022-03-01T04:47:23.841516'
statistics:
  total_words: 14128
  total_non_words: 1263
quality:
  non_words_ratio: 0.09
